// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX-ienqWEg8oOPuOFyzAyIu_jfJf-k4z4',
    appId: '1:556281758122:web:4ca8156cc21564e9af6bd3',
    messagingSenderId: '556281758122',
    projectId: 'bionic-soul-5b932',
    authDomain: 'bionic-soul-5b932.firebaseapp.com',
    storageBucket: 'bionic-soul-5b932.firebasestorage.app',
    measurementId: 'G-06LY12LK0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO9LZQ6sjGWBXZ91_XmjnIfLY-6TtbWxU',
    appId: '1:556281758122:android:77548fe54211a410af6bd3',
    messagingSenderId: '556281758122',
    projectId: 'bionic-soul-5b932',
    storageBucket: 'bionic-soul-5b932.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5k2PGP74SGsn2hRZFWv15ay5GwjmmwB4',
    appId: '1:556281758122:ios:fba6502ff40a3d9eaf6bd3',
    messagingSenderId: '556281758122',
    projectId: 'bionic-soul-5b932',
    storageBucket: 'bionic-soul-5b932.firebasestorage.app',
    iosBundleId: 'com.example.bionicSoulApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5k2PGP74SGsn2hRZFWv15ay5GwjmmwB4',
    appId: '1:556281758122:ios:fba6502ff40a3d9eaf6bd3',
    messagingSenderId: '556281758122',
    projectId: 'bionic-soul-5b932',
    storageBucket: 'bionic-soul-5b932.firebasestorage.app',
    iosBundleId: 'com.example.bionicSoulApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX-ienqWEg8oOPuOFyzAyIu_jfJf-k4z4',
    appId: '1:556281758122:web:6759bf99d58790f0af6bd3',
    messagingSenderId: '556281758122',
    projectId: 'bionic-soul-5b932',
    authDomain: 'bionic-soul-5b932.firebaseapp.com',
    storageBucket: 'bionic-soul-5b932.firebasestorage.app',
    measurementId: 'G-228RCMRJNJ',
  );
}
